### ISSUE TITLE
transactionCompleted Issue

### ISSUE THREAD

**Issue by AbdrahumanFikry** [nyartech/hyperpay#16]
`I/System.out(20605): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(20605): (HTTPLog)-Static: isSBSettingEnabled false
W/System.err(20605): java.lang.NullPointerException
W/System.err(20605): 	at com.nyartech.hyperpay.HyperpayPlugin.transactionCompleted(HyperpayPlugin.kt:290)
W/System.err(20605): 	at com.oppwa.mobile.connect.service.ConnectService.transactionCompleted(ConnectService.java:2)
W/System.err(20605): 	at com.oppwa.mobile.connect.provider.OppPaymentProvider.a(OppPaymentProvider.java:64)
W/System.err(20605): 	at com.oppwa.mobile.connect.provider.OppPaymentProvider.$r8$lambda$Z7rpKa2phFQX0DRjHjS8RQqzthY(Unknown Source:0)
W/System.err(20605): 	at com.oppwa.mobile.connect.provider.OppPaymentProvider$$ExternalSyntheticLambda1.run(Unknown Source:8)
W/System.err(20605): 	at java.lang.Thread.run(Thread.java:923)
I/System.out(20605): (HTTPLog)-Static: isSBSettingEnabled false
E/AndroidRuntime(20605): FATAL EXCEPTION: Thread-5
E/AndroidRuntime(20605): Process: com.example.test_hyperpay, PID: 20605
E/AndroidRuntime(20605): java.lang.IllegalStateException: null️
E/AndroidRuntime(20605): 	at com.nyartech.hyperpay.HyperpayPlugin.transactionCompleted(HyperpayPlugin.kt:319)
E/AndroidRuntime(20605): 	at com.oppwa.mobile.connect.service.ConnectService.transactionCompleted(ConnectService.java:2)
E/AndroidRuntime(20605): 	at com.oppwa.mobile.connect.provider.OppPaymentProvider.a(OppPaymentProvider.java:64)
E/AndroidRuntime(20605): 	at com.oppwa.mobile.connect.provider.OppPaymentProvider.$r8$lambda$Z7rpKa2phFQX0DRjHjS8RQqzthY(Unknown Source:0)
E/AndroidRuntime(20605): 	at com.oppwa.mobile.connect.provider.OppPaymentProvider$$ExternalSyntheticLambda1.run(Unknown Source:8)
E/AndroidRuntime(20605): 	at java.lang.Thread.run(Thread.java:923)
I/System.out(20605): (HTTPLog)-Static: isSBSettingEnabled false
I/ViewRootImpl@52cb303[MainActivity](20605): MSG_WINDOW_FOCUS_CHANGED 0 1
I/Process (20605): Sending signal. PID: 20605 SIG: 9
Lost connection to device.
`

----------------------------------------------------------------------------------------------------------------------
` override fun transactionCompleted(transaction: Transaction) {
        try {
            if (transaction.transactionType == TransactionType.SYNC) {
                // Send request to your server to obtain transaction status
                success("Transaction completed as synchronous.")
            } else {
                val uri = Uri.parse(transaction.redirectUrl)
                redirectData = ""

                val session =  mCustomTabsClient!!.newSession(object : CustomTabsCallback() {
                    override fun onNavigationEvent(navigationEvent: Int, extras: Bundle?) {
                        Log.w(TAG, "onNavigationEvent: Code = $navigationEvent")
                        when (navigationEvent) {
                            TAB_HIDDEN -> {
                                if(redirectData.isEmpty()) {
                                    redirectData = ""
                                    success("canceled")
                                } else {
                                    redirectData = ""
                                    Log.d(TAG, "Success, redirecting to app...")
                                    success("success")
                                }
                            }
                        }
                    }
                })

                val builder = CustomTabsIntent.Builder(session)
                val customTabsIntent = builder.build()
                customTabsIntent.intent.data = uri
                customTabsIntent.intent.flags = Intent.FLAG_ACTIVITY_NO_HISTORY
                customTabsIntent.launchUrl(mActivity!!, uri)

            }
        } catch (e: Exception) {
            e.printStackTrace()

            // Display error
            error("${e.message}️")
        }
    }`
My app crached after this error! 
Why Not opening WebView Page?

@pr-Mais @mal7othify @ialhashim @hadysata @ibraheem-nt

**Comment by AbdrahumanFikry** [comment]
[https://user-images.githubusercontent.com/41123719/129699558-ef1fafb7-099c-4b70-9a2d-b8a13f1a3ac1.gif](url)

My App crashes on the step when opening the web view page @pr-Mais
