### ISSUE TITLE
App Crashed when processed card 

### ISSUE THREAD

**Issue by awshakam1998** [nyartech/hyperpay#22]
After filling out the test card the app crashed and get me this error 
 ```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mozaic.www.shalati, PID: 6991
    java.lang.NoSuchMethodError: No virtual method setShareState(I)Landroidx/browser/customtabs/CustomTabsIntent$Builder; in class Landroidx/browser/customtabs/CustomTabsIntent$Builder; or its super classes (declaration of 'androidx.browser.customtabs.CustomTabsIntent$Builder' appears in /data/app/com.mozaic.www.shalati-mqnlSYOLNQIvJwqX_fg6Xg==/base.apk)
        at com.oppwa.mobile.connect.checkout.dialog.g0.a(Utils.java:48)
        at com.oppwa.mobile.connect.checkout.dialog.g0.b(Utils.java:7)
        at com.oppwa.mobile.connect.checkout.dialog.BaseActivity.d(BaseActivity.java:2)
        at com.oppwa.mobile.connect.checkout.dialog.BaseServiceActivity.c(BaseServiceActivity.java:35)
        at com.oppwa.mobile.connect.checkout.dialog.BaseServiceActivity.f(BaseServiceActivity.java:1)
        at com.oppwa.mobile.connect.checkout.dialog.BaseServiceActivity.lambda$E75Q2eQCU6wEesYxm2Iyx3fVKlc(Unknown Source:0)
        at com.oppwa.mobile.connect.checkout.dialog.-$$Lambda$BaseServiceActivity$E75Q2eQCU6wEesYxm2Iyx3fVKlc.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8349)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

the native code:

```
package com.mozaic.www.shalati

import android.content.Context
import android.content.Intent
import android.util.Log
import androidx.annotation.NonNull
import com.google.android.gms.common.ConnectionResult
import com.google.android.gms.common.GoogleApiAvailability
import com.huawei.hms.api.HuaweiApiAvailability
import com.oppwa.mobile.connect.checkout.meta.CheckoutSettings
import com.oppwa.mobile.connect.exception.PaymentError
import com.oppwa.mobile.connect.provider.Connect
import com.oppwa.mobile.connect.provider.Transaction
import com.oppwa.mobile.connect.provider.TransactionType
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel


class MainActivity : FlutterActivity() {
    private val hmsGsmCHANNEL = "com.mozaic.www.shalati/isHmsGmsAvailable"
    private val hyperPayCHANNEL = "com.mozaic.www.shalati/getPaymentMethod"
    var methodResult: MethodChannel.Result? = null
    var concurrentContext = this@MainActivity.context
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        //hmsGsmCHANNEL
        super.configureFlutterEngine(flutterEngine)
        MethodChannel(
            flutterEngine.dartExecutor.binaryMessenger,
            hmsGsmCHANNEL
        ).setMethodCallHandler { call, result ->
            // Note: this method is invoked on the main thread.

            if (call.method.equals("isHmsAvailable")) {
                result.success(isHmsAvailable())
            } else if (call.method.equals("isGmsAvailable")) {
                result.success(isGmsAvailable())
            } else {
                result.notImplemented()
            }
        }

        //hyperPayCHANNEL
        MethodChannel(
            flutterEngine.dartExecutor.binaryMessenger,
            hyperPayCHANNEL
        ).setMethodCallHandler { call, result ->
            // Note: this method is invoked on the main thread.
            if (call.method.equals("getPaymentMethod")) {
                methodResult = result
                val shopperUrl = "shalati://com.mozaic.www.shalati"
                // "F5188DE7144C4DEBBF5CBF4262CD056A.uat01-vm-tx03"
                val paymentBrands: Set<String> =setOf("VISA", "MASTER")

                print("CheckoutID: ${call.arguments as String} ------ \n")
                print("paymentBrands: $paymentBrands ------")
                val checkoutSettings = CheckoutSettings(
                    call.arguments as String,
                    paymentBrands,
                    Connect.ProviderMode.TEST
                )

                // Set shopper result URL
                checkoutSettings.setShopperResultUrl(shopperUrl)
                val intent: Intent = checkoutSettings.createCheckoutActivityIntent(this)
                startActivityForResult(intent, 242)
            } else {
                result.notImplemented()
            }
        }
    }

    private fun isHmsAvailable(): Boolean {
        var isAvailable = false
        val context: Context = concurrentContext
        if (null != context) {
            val result =
                HuaweiApiAvailability.getInstance().isHuaweiMobileServicesAvailable(context)
            isAvailable = ConnectionResult.SUCCESS == result
        }
        Log.i("MainActivity", "isHmsAvailable: $isAvailable")
        return isAvailable
    }

    private fun isGmsAvailable(): Boolean {
        var isAvailable = false
        val context: Context = concurrentContext
        if (null != context) {
            val result: Int =
                GoogleApiAvailability.getInstance().isGooglePlayServicesAvailable(context)
            isAvailable = com.google.android.gms.common.ConnectionResult.SUCCESS === result
        }
        Log.i("MainActivity", "isGmsAvailable: $isAvailable")
        return isAvailable
    }

    private fun paymentResult(result: String): String {
        return result
    }

    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent) {

        print("requestCode: $requestCode ------ \n")
        print("resultCode: $resultCode ------ \n")
        if (resultCode == 13) {
            when (resultCode) {
                100 -> {
                    /* transaction completed */
                    val transaction =
                        data.getParcelableExtra<Transaction>("com.oppwa.mobile.connect.checkout.dialog.CHECKOUT_RESULT_TRANSACTION")

                    /* resource path if needed */
                    val resourcePath =
                        data.getStringExtra("com.oppwa.mobile.connect.checkout.dialog.CHECKOUT_RESULT_RESOURCE_PATH")
                    if (transaction!!.transactionType == TransactionType.ASYNC) {
                        /* check the result of synchronous transaction */
                        methodResult!!.success(paymentResult("ASYNC"))
                    } else if (transaction.transactionType == TransactionType.SYNC) {
                        /* check the result of synchronous transaction */
                        methodResult!!.success(paymentResult("SYNC"))
                    } else {
                        /* wait for the asynchronous transaction callback in the onNewIntent() */
                        methodResult!!.success(paymentResult("FAIL"))
                    }
                }
                101 -> {
                    /* transaction canceled */
                    methodResult!!.success(paymentResult("CANCEL"))
                }
                102 -> {           /* error occurred */
                    val error: PaymentError
                    ? =
                        data.getParcelableExtra("com.oppwa.mobile.connect.checkout.dialog.CHECKOUT_RESULT_ERROR")
                    methodResult!!.success(paymentResult("ERROR"))

                }
            }
        } else if (requestCode == 17) {
            methodResult!!.success(paymentResult("ADDRESS"))
        }

    }


}

```
and the call from flutter code:

```
 static const platform =  MethodChannel("com.mozaic.www.shalati/getPaymentMethod");

  Future<void> _getPaymentResponse(String checkoutID, String mode) async {
    try {
      var result = await platform.invokeMethod(
          'getPaymentMethod', checkoutID);
      print('getPaymentMethod: ${result.toString()}');
    } on PlatformException catch (e) {
      print("Failed to get payment metohd: '${e.message}'.");
    }
  }
```

**Comment by pr-Mais** [comment]
Hello,
Are you using my [`hyperpay`](https://pub.dev/packages/hyperpay) package? if not, I cannot help you debug your own code. Try to use the package to integrate your app with HyperPay, if you faced any issues file one here please, thanks!
