### ISSUE TITLE
 leaked ServiceConnection

### ISSUE THREAD

**Issue by mhamTech** [nyartech/hyperpay#28]
Hello,
I am getting this error whenever I try to make payment, then I close the app on Android devices only.

E/ActivityThread( 6995): Activity io.flutter.embedding.android.FlutterActivity has leaked ServiceConnection com.nyartech.hyperpay.HyperpayPlugin$cctConnection$1@d6b85e0 that was originally bound here
E/ActivityThread( 6995): android.app.ServiceConnectionLeaked: Activity io.flutter.embedding.android.FlutterActivity has leaked ServiceConnection com.nyartech.hyperpay.HyperpayPlugin$cctConnection$1@d6b85e0 that was originally bound here
E/ActivityThread( 6995): 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1934)
E/ActivityThread( 6995): 	at android.app.LoadedApk.getServiceDispatcherCommon(LoadedApk.java:1806)
E/ActivityThread( 6995): 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1785)
E/ActivityThread( 6995): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1965)
E/ActivityThread( 6995): 	at android.app.ContextImpl.bindService(ContextImpl.java:1896)
E/ActivityThread( 6995): 	at android.content.ContextWrapper.bindService(ContextWrapper.java:810)
E/ActivityThread( 6995): 	at androidx.browser.customtabs.CustomTabsClient.bindCustomTabsService(CustomTabsClient.java:80)
E/ActivityThread( 6995): 	at com.nyartech.hyperpay.HyperpayPlugin.onMethodCall(HyperpayPlugin.kt:189)
E/ActivityThread( 6995): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/ActivityThread( 6995): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/ActivityThread( 6995): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
E/ActivityThread( 6995): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/ActivityThread( 6995): 	at android.os.Handler.handleCallback(Handler.java:938)
E/ActivityThread( 6995): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/ActivityThread( 6995): 	at android.os.Looper.loopOnce(Looper.java:201)
E/ActivityThread( 6995): 	at android.os.Looper.loop(Looper.java:288)
E/ActivityThread( 6995): 	at android.app.ActivityThread.main(ActivityThread.java:7813)
E/ActivityThread( 6995): 	at java.lang.reflect.Method.invoke(Native Method)
E/ActivityThread( 6995): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/ActivityThread( 6995): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

I had this problem previously on an old hyperpay sdk, I could solve it by adding this to MainActivity.java :
    @Override
    public void onDestroy() {
        super.onDestroy();

        if (serviceConnection != null) {
            unbindService(serviceConnection);
        }
    }

But I don't know how to solve it in Kotlin, please help, it is making my crashlytics a nightmare

**Comment by pr-Mais** [comment]
I believe this's already done here: 
https://github.com/nyartech/hyperpay/blob/57c10845389eace2ee5d3bfa08a21520d739a35b/android/src/main/kotlin/com/nyartech/hyperpay/HyperpayPlugin.kt#L121-L122
I have Crashlytics setup in an app using this plugin, but I don't see any crashes related to it, can you give an example please?

**Comment by mhamTech** [comment]
<img width="1275" alt="Screen Shot 2022-09-04 at 10 39 42 AM" src="https://user-images.githubusercontent.com/66898244/188302948-e3a7088a-7153-4782-85ae-467cd20da592.png">

This is the problem on Crashlytics, 
and I already have this snippet in the code

`    override fun onDetachedFromActivity() {
        if (intent != null) {
            mActivity!!.stopService(intent)
            mActivity!!.unbindService(hyperpayConnection)
        }

        hiddenLifecycleReference?.lifecycle?.removeObserver(lifecycleObserver)
        hiddenLifecycleReference = null
        mActivity = null
    }`

**Comment by pr-Mais** [comment]
Could you try the latest update from the `main` branch? I removed the service connection completely, but pay attention to the [migration notes here](https://github.com/nyartech/hyperpay#migration-to-v100).

**Comment by mhamTech** [comment]
I have tried the newest code from this repository and the problem still exist

**Comment by pr-Mais** [comment]
Please change the dependency over the package to:
```yaml
hyperpay:
  git:
    url: https://github.com/nyartech/hyperpay.git
    ref: v1.0.0-dev.3
```
The new version was not published to pub due to size constraints by pub.dev, I'm working out a solution to remove the embedded `xcframework` from the bundled plugin, but for now please use git dependency with the version tag.
